import { useState } from "react";
import { BrowserRouter, Link, useLocation } from "react-router-dom";
import logo from "./assets/zurilofts-logo.png";
import "./index.css";

function Header({ onMenu }) {
  return <header className="zl-header"><Link to="/" className="zl-brand"><img src={logo} alt="ZuriLofts" /><span>ZuriLofts</span></Link><nav className="zl-desktop-nav"><Link to="/properties">Properties</Link><Link to="/favourites">Saved</Link><Link to="/trips">Trips</Link><Link to="/inbox">Messages</Link></nav><div className="zl-header-actions"><button className="zl-icon-btn" aria-label="Notifications">◌</button><span className="zl-avatar">NB</span><span className="zl-user-name">Nate</span><span className="zl-language">English⌄</span><button className="zl-menu-btn" onClick={onMenu} aria-label="Open menu">☰</button></div></header>;
}
function MobileNav() { return <nav className="zl-mobile-nav"><Link to="/"><span>⌂</span><small>Home</small></Link><Link to="/properties"><span>⌕</span><small>Explore</small></Link><Link to="/trips"><span>◷</span><small>Trips</small></Link><Link to="/inbox"><span>◌</span><small>Inbox</small></Link><Link to="/profile"><span>◯</span><small>Profile</small></Link></nav>; }
function MenuModal({ onClose }) { return <div className="zl-modal-backdrop" onClick={onClose}><div className="zl-menu-modal" onClick={(e) => e.stopPropagation()}><div className="zl-modal-top"><span className="zl-avatar">NB</span><strong>Nate</strong><span className="zl-language">English⌄</span><button className="zl-icon-btn" onClick={onClose}>×</button></div><div className="zl-modal-links"><p className="zl-overline">MORE TO EXPLORE</p><Link to="/places" onClick={onClose}>Places to Visit</Link><Link to="/restaurants" onClick={onClose}>Restaurants</Link><Link to="/guides" onClick={onClose}>Travel Guides</Link><Link to="/favourites" onClick={onClose}>Favourites</Link><Link to="/shortlists" onClick={onClose}>Shortlists</Link></div><div className="zl-modal-actions"><Link className="ui-btn-primary" to="/profile" onClick={onClose}>My Profile</Link><Link className="ui-btn-secondary" to="/booking-history" onClick={onClose}>Booking History</Link><Link className="ui-btn-secondary" to="/terms" onClick={onClose}>Terms of Service</Link><Link className="ui-btn-secondary" to="/privacy" onClick={onClose}>Privacy Policy</Link><Link className="ui-btn-strong" to="/admin" onClick={onClose}>Admin Panel</Link><button className="zl-signout">Sign Out</button></div></div></div>; }
const stays = ["Harbor Loft", "Garden Studio", "City Apartment", "Westlands Hideaway"];
function Home() { return <main><section className="zl-hero"><div className="zl-hero-copy"><p className="zl-overline">FURNISHED STAYS IN NAIROBI</p><h1>Find a place that feels like yours.</h1><p>Thoughtfully furnished apartments, trusted hosts, and neighbourhoods worth staying for.</p><Link className="ui-btn-primary" to="/properties">Explore stays</Link></div><div className="zl-search-card"><label>Where</label><input className="ui-input" placeholder="Search Nairobi neighbourhoods" /><div className="zl-search-grid"><div><label>Check in</label><div className="zl-field">Add dates</div></div><div><label>Guests</label><div className="zl-field">Add guests</div></div><button className="ui-btn-strong">Search</button></div></div></section><section className="zl-section"><div className="zl-section-head"><div><p className="zl-overline">STAYS YOU'LL LOVE</p><h2>Comfort, with a local point of view.</h2></div><Link to="/properties" className="zl-text-link">See all stays →</Link></div><div className="zl-card-grid">{stays.map((stay, i) => <article className="zl-stay-card" key={stay}><div className={'zl-photo photo-'+i}></div><div className="zl-card-body"><div className="zl-card-row"><h3>{stay}</h3><span>♡</span></div><p>{i % 2 ? "2 beds · Kilimani" : "1 bed · Westlands"}</p><strong>KES {(12000 + i * 2500).toLocaleString()} <small>night</small></strong></div></article>)}</div></section><section className="zl-trust"><div><p className="zl-overline">WHY ZURILOFTS</p><h2>Stay with confidence.</h2></div><div className="zl-trust-grid"><div><b>Verified homes</b><p>Every listing is reviewed for quality and accuracy.</p></div><div><b>Local support</b><p>Real people who know Nairobi are here when you need them.</p></div><div><b>Flexible booking</b><p>Clear policies and thoughtful options for your plans.</p></div></div></section></main>; }
function GenericPage({ title, eyebrow, description, admin = false }) { const cards = admin ? ["Arrivals today", "Active listings", "Pending reviews", "Net earnings"] : ["Upcoming stay", "Saved homes", "Messages", "Profile completion"]; return <main className="zl-page"><div className="zl-page-heading"><div><p className="zl-overline">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div><button className="ui-btn-primary">{admin ? "Create listing" : "Explore stays"}</button></div><div className="zl-metric-grid">{cards.map((c, i) => <div className="zl-metric" key={c}><span>{c}</span><strong>{admin ? ["5", "12", "3", "KES 184,200"][i] : ["2", "8", "4", "72%"][i]}</strong><small>{i === 0 ? "This month" : "Updated today"}</small></div>)}</div><section className="zl-panel"><div className="zl-panel-head"><h2>{admin ? "Operational overview" : "Your activity"}</h2><button className="ui-btn-secondary">View all</button></div><div className="zl-list">{["Harbor Loft", "Garden Studio", "City Apartment"].map((x, i) => <div className="zl-list-row" key={x}><div className="zl-list-thumb"></div><div className="zl-list-copy"><b>{x}</b><span>{i === 0 ? "Confirmed · 20 May" : i === 1 ? "Awaiting response" : "Saved · 3 days ago"}</span></div><button className="zl-icon-btn" aria-label="More actions">⋯</button></div>)}</div></section></main>; }
function AppShell() { const location = useLocation(); const [menuOpen, setMenuOpen] = useState(false); const path = location.pathname; const isAdmin = path.startsWith("/admin") || path.startsWith("/host"); const content = path === "/" ? <Home /> : path === "/properties" ? <GenericPage title="Find your next stay" eyebrow="EXPLORE NAIROBI" description="Browse verified furnished homes with clear pricing and flexible dates." /> : path === "/admin" ? <GenericPage admin title="Admin operations" eyebrow="ZURILOFTS · OPERATIONS" description="Keep listings, bookings, hosts, and guest support moving." /> : path.startsWith("/host") ? <GenericPage admin title="Host workspace" eyebrow="HOST OPERATIONS" description="Manage your listings, calendar, earnings, and guest conversations." /> : <GenericPage title={path === "/inbox" ? "Messages" : path === "/trips" ? "Your trips" : path === "/profile" ? "Your profile" : "ZuriLofts"} eyebrow="ZURILOFTS" description="A calm, clear place to manage your ZuriLofts experience." />; return <div className="zl-app"><Header onMenu={() => setMenuOpen(true)} />{content}<MobileNav />{menuOpen && <MenuModal onClose={() => setMenuOpen(false)} />}{isAdmin && <div className="zl-role-pill">{path.startsWith("/host") ? "Host" : "Admin"}</div>}</div>; }
export default function App() { return <BrowserRouter><AppShell /></BrowserRouter>; }
